apiVersion: v1
kind: Namespace
metadata:
  name: dnsmasq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq
  namespace: dnsmasq
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: dnsmasq
  template:
    metadata:
      labels:
        app: dnsmasq
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: dnsmasq
        image: welasco/dnsmasq
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: dnsmasqParameters
          value: "--address=/#/192.168.2.1 --log-queries=extra --log-dhcp --log-debug"
        ports:
        - protocol: UDP
          containerPort: 53
        - protocol: TCP
          containerPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: dnsmasq-service
  namespace: dnsmasq
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    app: dnsmasq
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-dnsmasq
  namespace: dnsmasq
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dnsmasq
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60